### ISSUE TITLE
Crash when clicking on the "Avatar, Bio, and Display Name" setting 

### ISSUE THREAD

**Issue by lipgi** [pixelfed/pixelfed-rn#29] opened 2024-06-27 23:16 UTC
in the black and white icon "pixelfed" Android app version 1.0.0
Bug report:

![Screenshot_2024-06-28-07-13-59-107_cn wps moffice_eng](https://github.com/pixelfed/pixelfed-rn/assets/173347205/5da3ec9e-4ded-409d-baf8-2b9e757a82bc)

06-28 06:59:34.072  1000   799   895 I libPowerHal: [perfLockRel] hdl:31800, idx:1
06-28 06:59:34.072  1000   799   895 I libPowerHal: MTKPOWER_HINT_APP_TOUCH: cpu_ctrl set cpu freq: -1 -1 -1 -1
06-28 06:59:34.073  1000   799   895 I libPowerHal: MTKPOWER_HINT_APP_TOUCH: set gpu opp level: 31
06-28 06:59:34.073  1000   799   895 I libPowerHal: MTKPOWER_HINT_APP_TOUCH: set gpu opp level max: 0
06-28 06:59:34.073  1000   799   895 I libPowerHal: [PD] MTKPOWER_HINT_APP_TOUCH update cmd:1000000, param:-1
06-28 06:59:34.073  1000   799   895 I libPowerHal: [PD] MTKPOWER_HINT_APP_TOUCH update cmd:1408100 param:0
06-28 06:59:34.073  1000   799   895 I libPowerHal: [PD] (more) /proc/perfmgr/boost_ctrl/eas_ctrl/perfserv_prefer_idle set +prefix:1 0;
06-28 06:59:34.073  1000   799   895 I libPowerHal: [PD] MTKPOWER_HINT_APP_TOUCH update cmd:410000 param:0
06-28 06:59:34.073  1000   799   895 I libPowerHal: [PD] MTKPOWER_HINT_APP_TOUCH update cmd:1408100 param:0
06-28 06:59:34.076  1000   799   895 I libPowerHal: [PD] MTKPOWER_HINT_APP_TOUCH update cmd:1408300 param:0
06-28 06:59:34.078  1000   799   895 I libPowerHal: [PD] MTKPOWER_HINT_APP_TOUCH update cmd:3408600 param:0
06-28 06:59:34.078  1000   799   895 I libPowerHal: [PD] MTKPOWER_HINT_APP_TOUCH update cmd:1000000 param:-1
06-28 06:59:34.130  1000   799   876 I libPerfCtl: xgfGetFPS pid:2149 fps:-1
06-28 06:59:34.131  1000   799   876 I libPerfCtl: xgfGetFPS pid:2162 fps:-1
06-28 06:59:34.131  1000   799   876 I libPerfCtl: xgfGetFPS pid:22665 fps:-1
06-28 06:59:34.131  1000   799   876 I libPerfCtl: xgfGetFPS pid:28673 fps:-1
06-28 06:59:34.131  1000   799   876 I libPowerHal: [updateFPS] pid(28673) : 90 => -1
06-28 06:59:34.131  1000   799   895 I libPowerHal: [perfNotifyAppState] pack:com.pixelfed.android, act:com.pixelfed.android.MainActivity, state:5, pid:28673, uid:10733, fps:-1
06-28 06:59:34.132  1000   799   895 E UxUtility: notifyAppState error = NULL
06-28 06:59:34.132  1000   799   895 I TouchUtility: notifyAppState error = NULL
06-28 06:59:34.133  1000   799   876 I libPerfCtl: xgfGetFPS pid:31342 fps:-1
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: Process: com.pixelfed.android, PID: 28673
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'borderBottomWidth' in shadow node of type: RCTView
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:125)
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:321)
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:248)
06-28 06:59:34.175 10733 28673 28738 E AndroidRuntime: 	at

**Comment by dansup** [comment] 2024-06-28 00:07
Duplicate of #7

**Closed by dansup** 2024-06-28 00:07 UTC
